# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "CODTracked Prod"
application_url = "https://app.codtracked.com/"
embedded = false
client_id = "0db071e09f21f8daacb901189df7457b"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_fulfillments,read_locations,read_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://app.codtracked.com/api/integrations/shopify/callback"
]

[webhooks]
api_version = "2026-07"
